## output directories
derivatives: derivatives
xray_from_ct: xray_from_ct
xray_from_mask: xray_from_mask
xray_from_ctmask: xray_rom_ctmask
seg_roi: seg_roi
ct_roi: ct_roi
ct_mask_roi: ct_mask_roi
centroid: centroid_roi
overlay: overlay