---

# subject-list
subjects:
  subject_basepath: 2D-3D-Reconstruction-Datasets/totalsegmentator/Totalsegmentator_dataset
  subject_list: configs/subjects_list/subjects_30k.lst

# xray image properties
xray_pose:
  _load: xray_pose_conf/${ROI_properties.axcode}_pose.yaml
  res: ${ROI_properties.res}
  size: ${ROI_properties.size}
  drr_from_ct_mask: ${ROI_properties.drr_from_ct_mask}
  drr_from_mask: ${ROI_properties.drr_from_mask}
  
# output directories
out_directories:
  _load: directory_conf/dir_ct.yaml

# ROI extraction properties
ROI_properties:
  axcode: PIR
  is_left: False
  ct_padding: -1024
  seg_padding: 0
  drr_from_ct_mask: False
  drr_from_mask: False
  res: 1.0
  size: 128

# filename conventions
filename_convention:
  input:
    ct: "ct.nii.gz"
    seg: "segmentations/femur_right.nii.gz"
    ctd: ""
  output:
    xray_ap: "{id}_femur_right-ap.png"
    xray_lat: "{id}_femur_right-lat.png"
    xray_mask_ap: "{id}_femur_right_mask-ap.png"
    xray_mask_lat: "{id}_femur_right_mask-lat.png"        
    ct_roi: '{id}_femur_right-ct.nii.gz' 
    ct_mask_roi: '{id}_femur_right-ct-mask.nii.gz' 
    seg_roi: '{id}_femur_right_msk.nii.gz'
